#!/usr/bin/env python3
"""Exact regression for FIXED_THRESHOLD_ADJACENT_LAYER_COUNTEREXAMPLE.

The theorem is asymptotic.  This script reconstructs its two exact integer
recurrences and checks the finite strong-glue lower bound through eight
padding depths.  Floating point is used only to display logarithms of
positive exact integers.
"""

from __future__ import annotations

from fractions import Fraction
from math import comb
from pathlib import Path
import importlib.util
import sys


HERE = Path(__file__).resolve().parent


def load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


CE = load(
    "fixed_threshold_capped_e",
    HERE / "agent_asymptotic" / "capped_e_counterexample.py",
)


def top_cap_rows(maximum: int) -> list[list[int]]:
    """t(m,i), using the exact Pascal maximum-cap recurrence."""
    rows = [[1]]
    for m in range(1, maximum + 1):
        previous = rows[-1]
        current = [0] * (m + 1)
        current[0] = 1
        for i in range(1, m):
            current[i] = comb(m - 1, i) * previous[i - 1] + previous[i]
        rows.append(current)
    return rows


def exact_log2(value: int) -> float:
    return CE.log2_int(value)


def main() -> None:
    maximum_j = 280
    rows = top_cap_rows(maximum_j)

    padding = CE.LEAF
    padding_size = 1
    exact_rows: list[tuple[int, int, int]] = []

    for depth in range(1, 9):
        template = CE.PrefixPascal(41, 27, 1 << 35)
        padding, padding_size = template.evaluate(padding, padding_size)
        assert padding_size == 1 << (35 * depth)

        raw_rank = 35 * depth
        rank = raw_rank if raw_rank % 2 == 0 else raw_rank + 1
        assert rank <= maximum_j

        core_size = comb(rank, rank // 2)
        core, evaluated_size = CE.PrefixPascal(
            rank, rank // 2, core_size
        ).evaluate(CE.LEAF, 1)
        assert evaluated_size == core_size

        one_sided = rows[rank - 1][rank // 2 - 1]
        assert one_sided > 0

        # The coefficientwise recurrence gives
        # v_(j+1)(core prec padding) <= V(padding)+C(core)U(padding).
        denominator = padding.convex + core.cap * padding.cup
        assert denominator > 0
        lower_bits = 2 * exact_log2(one_sided) - exact_log2(denominator)

        # Each scalar state is itself generated by exact strong glue.
        assert core.convex >= one_sided * one_sided
        assert core.cap >= one_sided
        exact_rows.append((depth, rank, round(1000 * lower_bits)))

        if depth >= 5:
            assert one_sided * one_sided > denominator

    # Coarse rational margins used in the proof:
    # beta > 5/8 > 41/70 and beta/2+1/5 < 23/40 < 41/70.
    assert Fraction(5, 8) > Fraction(41, 70)
    assert Fraction(23, 40) < Fraction(41, 70)
    assert Fraction(5, 8) - Fraction(41, 70) == Fraction(11, 280)

    last_bits = exact_rows[-1][2] / 1000
    assert last_bits > 1600
    print(
        "PASS: exact fixed-threshold adjacent-layer counterexample; "
        f"rows={exact_rows}; last_lower_bits={last_bits:.3f}"
    )


if __name__ == "__main__":
    main()
