#!/usr/bin/env python3
"""Adversarial tests for the Pinsker-calibrated strong-glue profile.

This script has three reproducible parts:

1. It constructs a mirror-paired Pascal iterate proving that CU/W can have a
   positive quadratic logarithmic exponent.
2. It exhaustively checks the quadratic profile through 13 leaves.
3. It runs a deterministic exact-integer recursive beam and exhibits a valid
   893-leaf merge that kills the natural inherited-margin Bellman induction.

Only reporting logarithms uses floating point.  Every state is generated by
the exact integer strong-glue recurrences.
"""

from __future__ import annotations

import argparse
import math
import random
from dataclasses import dataclass
from decimal import Decimal, localcontext

from tree_potential_adversary import (
    KAPPA,
    LEAF,
    PrefixPascal,
    State,
    glue,
    log2_int,
)


def mirror(state: State) -> State:
    return State(state.cup, state.cap, state.convex)


def psi(state: State) -> float:
    lc = log2_int(state.cap)
    lu = log2_int(state.cup)
    radial = lc + lu
    correction = KAPPA * (lc - lu) ** 2 / radial if radial else 0.0
    return log2_int(state.convex) - correction


def margin(state: State, size: int) -> float:
    return psi(state) - 0.5 * math.log2(size) ** 2


def high_precision_margin(state: State, size: int, precision: int = 80) -> Decimal:
    """Evaluate the transcendental profile with a wide Decimal margin."""
    with localcontext() as ctx:
        ctx.prec = precision
        ln2 = Decimal(2).ln()
        lc = Decimal(state.cap).ln() / ln2
        lu = Decimal(state.cup).ln() / ln2
        lw = Decimal(state.convex).ln() / ln2
        logn = Decimal(size).ln() / ln2
        kappa = Decimal(1) / (Decimal(2) * ln2)
        correction = kappa * (lc - lu) ** 2 / (lc + lu) if lc + lu else 0
        return lw - correction - logn**2 / Decimal(2)


def comparison_counterexample(iterations: int = 20) -> None:
    """Kill CU/W <= 2^o(log^2 n) by a mirror-paired iterate."""
    template = PrefixPascal(41, 27, 1 << 35)
    x = LEAF
    size = 1
    print("mirror-paired comparison counterexample")
    print("base template=prefix(T(41,27),2^35), degrees=(27,14)")
    for t in range(1, iterations + 1):
        x, size = template.evaluate(x, size)
        root = glue(mirror(x), x, size, size)
        root_size = 2 * size
        gap = (
            log2_int(root.cap)
            + log2_int(root.cup)
            - log2_int(root.convex)
        )
        if t in {1, 2, 3, 5, 10, 13, 15, 20}:
            logn = math.log2(root_size)
            print(
                f"t={t:2d} log2(n)={logn:7.1f} "
                f"log2(CU/W)={gap:14.6f} "
                f"gap/log2(n)={gap/logn:10.6f} "
                f"gap/log2(n)^2={gap/logn**2:10.6f}"
            )
    print(
        "proved limiting quadratic coefficient: "
        "(27-14)/(2*35)=13/70=",
        13 / 70,
    )


def exhaustive(nmax: int = 13) -> None:
    """Exhaust all distinct exact triples and report profile/kappa margins."""
    states: list[set[tuple[int, int, int]]] = [set() for _ in range(nmax + 1)]
    states[1] = {(1, 1, 1)}
    running_kappa = math.inf
    print("exhaustive profile search")
    for n in range(2, nmax + 1):
        current: set[tuple[int, int, int]] = set()
        for a in range(1, n):
            b = n - a
            for ca, ua, wa in states[a]:
                for cb, ub, wb in states[b]:
                    current.add(
                        (
                            cb + (b + 1) * ca,
                            ua + (a + 1) * ub,
                            wa + wb + ca * ub,
                        )
                    )
        states[n] = current
        minimum_margin = math.inf
        for values in current:
            state = State(*values)
            minimum_margin = min(minimum_margin, margin(state, n))
            lc = log2_int(state.cap)
            lu = log2_int(state.cup)
            if lc != lu:
                allowed = (
                    (log2_int(state.convex) - 0.5 * math.log2(n) ** 2)
                    * (lc + lu)
                    / (lc - lu) ** 2
                )
                running_kappa = min(running_kappa, allowed)
        print(
            f"n={n:2d} states={len(current):7d} "
            f"min_margin={minimum_margin: .9f} "
            f"small-state_kappa_ceiling={running_kappa: .9f}"
        )


@dataclass(frozen=True)
class BeamItem:
    state: State
    tree: str


def recursive_beam(nmax: int = 1000, pool_size: int = 120) -> None:
    """Search valid triples and disprove inherited-margin monotonicity.

    The deterministic beam retains low-margin states and one state in every
    coarse imbalance bin.  Its purpose is falsification, not certification of
    the profile beyond the exhaustive range.
    """
    rng = random.Random(838)
    pools: list[list[BeamItem]] = [[] for _ in range(nmax + 1)]
    pools[1] = [BeamItem(LEAF, "1")]
    worst_gap = math.inf
    witness = None
    global_minimum = math.inf
    print("deterministic recursive beam")
    for n in range(2, nmax + 1):
        candidates: dict[State, str] = {}
        splits = {1, n - 1, n // 2, max(1, n // 3), max(1, 2 * n // 3)}
        splits |= {rng.randrange(1, n) for _ in range(30)}
        for a in splits:
            b = n - a
            for _ in range(20):
                left_item = rng.choice(pools[a])
                right_item = rng.choice(pools[b])
                parent = glue(left_item.state, right_item.state, a, b)
                candidates.setdefault(
                    parent, f"({left_item.tree}<{right_item.tree})"
                )
                reflected = mirror(parent)
                candidates.setdefault(reflected, "R" + candidates[parent])
                gap = margin(parent, n) - min(
                    margin(left_item.state, a), margin(right_item.state, b)
                )
                if gap < worst_gap:
                    worst_gap = gap
                    witness = (
                        n,
                        a,
                        left_item,
                        right_item,
                        BeamItem(parent, candidates[parent]),
                    )

        ordered = sorted(candidates, key=lambda state: margin(state, n))
        retained = ordered[: pool_size // 2]
        bins: dict[int, State] = {}
        for state in ordered:
            lc = log2_int(state.cap)
            lu = log2_int(state.cup)
            bins.setdefault(round(20 * (lc - lu) / (lc + lu)), state)
        retained += list(bins.values())
        while len(retained) < pool_size:
            retained.append(rng.choice(ordered))
        retained = list(dict.fromkeys(retained))[:pool_size]
        pools[n] = [BeamItem(state, candidates[state]) for state in retained]
        global_minimum = min(global_minimum, *(margin(item.state, n) for item in pools[n]))
        if n % 100 == 0:
            print(
                f"n={n:4d} worst_local_gap={worst_gap: .9f} "
                f"retained_min_margin={min(margin(x.state,n) for x in pools[n]): .9f}"
            )

    assert witness is not None
    n, a, left_item, right_item, parent_item = witness
    b = n - a
    left_margin = high_precision_margin(left_item.state, a)
    right_margin = high_precision_margin(right_item.state, b)
    parent_margin = high_precision_margin(parent_item.state, n)
    hp_gap = parent_margin - min(left_margin, right_margin)
    print("exact valid local-induction witness")
    print(f"sizes: a={a}, b={b}, n={n}")
    print(f"left  (C,U,W)={left_item.state}")
    print(f"right (C,U,W)={right_item.state}")
    print(f"parent(C,U,W)={parent_item.state}")
    print(
        "high-precision margins: "
        f"left={left_margin}, right={right_margin}, parent={parent_margin}"
    )
    print(f"parent-min(children)={hp_gap}")
    print(
        f"tree certificate lengths: left={len(left_item.tree)}, "
        f"right={len(right_item.tree)}, parent={len(parent_item.tree)}"
    )
    assert n == 893 and a == 515
    assert left_item.state == State(
        278088873137502,
        88272696090590218,
        369399013621622451658622880,
    )
    assert right_item.state == State(
        3360930061559256384,
        1224756619015,
        114026966966178909384382679,
    )
    assert parent_item.state == State(
        3466325744478369642,
        88904670506001958,
        824017168637379565765806089,
    )
    assert hp_gap < Decimal(-5)
    assert global_minimum > 0


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--comparison", action="store_true")
    parser.add_argument("--exhaustive", type=int, default=0, metavar="N")
    parser.add_argument("--beam", type=int, default=0, metavar="N")
    args = parser.parse_args()
    if not (args.comparison or args.exhaustive or args.beam):
        args.comparison = True
        args.exhaustive = 13
        args.beam = 1000
    if args.comparison:
        comparison_counterexample()
    if args.exhaustive:
        exhaustive(args.exhaustive)
    if args.beam:
        recursive_beam(args.beam)


if __name__ == "__main__":
    main()
