#!/usr/bin/env python3
"""Checks EXCESS_RANK_PREFIX_STAR_COHERENCE_GATE.md."""

from fractions import Fraction as Q
from itertools import product


def prefix_star(s, k, d):
    zero = (0,) * s
    words = {
        tuple(core) + (0,) * (s - k)
        for core in product(range(d), repeat=k)
    }
    for role in range(k, s):
        for label in range(1, d):
            word = list(zero)
            word[role] = label
            words.add(tuple(word))
    return words


def follow_zero_path(words, s, d):
    survivors = set(words)
    branching = []
    for role in range(s):
        classes = {
            label: {word for word in survivors if word[role] == label}
            for label in range(d)
        }
        nonempty = {label: fibre for label, fibre in classes.items() if fibre}
        branching.append(len(nonempty))
        assert len(nonempty) == d
        # Zero is a heaviest class; ties are broken toward zero.
        assert len(nonempty[0]) == max(map(len, nonempty.values()))
        survivors = nonempty[0]
    assert survivors == {(0,) * s}
    return branching


def check_instance(s, k, d):
    words = prefix_star(s, k, d)
    assert len(words) == d**k + (s - k) * (d - 1)

    branching = follow_zero_path(words, s, d)
    path_cost = 1
    for amount in branching:
        path_cost *= amount
    assert path_cost == d**s
    assert (d**s) // path_cost == 1

    # No selected word contains nonzero labels in two distinct tail roles.
    for i in range(k, s):
        for j in range(i + 1, s):
            for left in range(1, d):
                for right in range(1, d):
                    codegree = sum(
                        word[i] == left and word[j] == right for word in words
                    )
                    assert codegree == 0

    # A full bad box on any four tail roles is disjoint from every selected
    # word, hence consistent with the hereditary complex generated by words.
    if s - k >= 4:
        roles = tuple(range(k, k + 4))
        bad_box = set(product(range(1, d), repeat=4))
        assert bad_box
        for word in words:
            trace = tuple(word[role] for role in roles)
            assert trace not in bad_box


def weighted_prefix_star(s, k, d):
    h = s - k
    zero_tail = (0,) * h
    tails = {zero_tail: Q(1, d**h)}
    for role in range(h):
        for label in range(1, d):
            tail = [0] * h
            tail[role] = label
            tails[tuple(tail)] = Q(1, d ** (role + 1))
    assert sum(tails.values(), Q(0)) == 1
    return {
        tuple(core) + tail: weight
        for core in product(range(d), repeat=k)
        for tail, weight in tails.items()
    }


def check_weighted_instance(s, k, d):
    records = weighted_prefix_star(s, k, d)
    assert sum(records.values(), Q(0)) == d**k
    assert all(Q(0) < weight <= 1 for weight in records.values())
    survivors = dict(records)
    cost = Q(1)
    for role in range(s):
        classes = {
            label: {
                word: weight
                for word, weight in survivors.items()
                if word[role] == label
            }
            for label in range(d)
        }
        masses = {
            label: sum(fibre.values(), Q(0))
            for label, fibre in classes.items()
        }
        assert len(set(masses.values())) == 1
        total = sum(masses.values(), Q(0))
        ratio = total / masses[0]
        assert ratio == d
        cost *= ratio
        survivors = classes[0]
    assert survivors == {(0,) * s: Q(1, d ** (s - k))}
    terminal_mass = next(iter(survivors.values()))
    assert terminal_mass * cost == d**k
    assert Q(d**s, 1) / cost == 1

    for i in range(k, s):
        for j in range(i + 1, s):
            assert not any(word[i] != 0 and word[j] != 0 for word in records)


def main():
    for instance in [
        (5, 1, 2),
        (7, 2, 3),
        (9, 3, 2),
        (10, 4, 4),
        (12, 5, 3),
    ]:
        check_instance(*instance)
        check_weighted_instance(*instance)
    print("EXCESS_RANK_PREFIX_STAR_COHERENCE_GATE verifier: PASS")


if __name__ == "__main__":
    main()
